swagger: "2.0"
info:
  version: 1.0.0
  title: E-Commerce
  description: Public API
  contact:
    email: temp@gmail.com
  license:
    name: Apache 2.0
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: localhost:1234

basePath: /
schemes:
#  - https
- http
tags:
- name: user
  description: all functions related user accounts

paths:
  /user:
    post:
      tags:
      - "user"
      summary: add new user
      operationId: adduser
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: body
        required: true
        schema:
          type: object
          properties:
            name:
              type: string
            email:
              type: string
            mobile:
              type: string
            userType:
              type: string
              default: "superAdmin"
              enum:
              - admin
              - user
            gender:
              type: string
              enum:
              - Male
              - Female
            password:
              type: string
            allowNotification:
              type: boolean
            address:
              type: object
              properties:
                street:
                  type: string
                city:
                  type: string
                state:
                  type: string
                pincode:
                  type: string
            cart:
              type: string
      responses:
        "200":
          description: successful operation
          schema:
            $ref: "#/definitions/ApiResponse"
    get:
      tags:
      - "user"
      summary: Get all users details
      operationId: getAllUsers
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/ApiResponse'

  /user/{_id}:
    get:
      tags:
      - "user"
      summary: Get user details
      operationId: getUser
      consumes:
      - application/json

      produces:
      - application/json
      parameters:
      - in: path
        name: _id
        description: _id  of the user
        required: true
        type: string
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/ApiResponse'
    put:
      tags:
      - "user"
      summary: update user
      operationId: userUpdate
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: path
        name: _id
        description: _id  of the user
        required: true
        type: string
      - in: body
        name: body
        required: true
        schema:
          type: object
          properties:
          mobile:
            type: string
          email:
            type: string
          gender:
            type: string
            enum:
            - Male
            - Female
          userType:
            type: string
            default: "admin"
            enum:
            - admin
            - user
          name:
            type: string
          password:
            type: string
          allowNotification:
            type: boolean
          address:
            type: object
            properties:
              street:
                type: string
              city:
                type: string
              state:
                type: string
              pincode:
                type: string
      responses:
        "200":
          description: successful operation
            schema:
              $ref: "#/definitions/ApiResponse"
    delete:
      tags:
      - "user"
      summary: delete user
      operationId:  deleteUser
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: path
        name: _id
        description: _id  of the user
        required: true
        type: string
      security:
      - bearerAuth: []
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/ApiResponse'

  
securityDefinitions:
  bearerAuth:
    type: apiKey
    name: Authorization
    in: header
definitions:
  ApiResponse:
    type: object
    properties:
      type:
        type: string
      success:
        type: boolean
      error:
        type: boolean
      message:
        type: string
      data:
        type: object

